# Generated by Django 3.1.6 on 2021-02-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'senior'), (3, 'external'), (4, 'admin')], verbose_name='user type'),
        ),
    ]
