# Generated by Django 3.1.6 on 2021-02-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210221_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='profile image'),
        ),
    ]
