# Generated by Django 3.1.6 on 2021-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_backend-group-model_20210222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='active'),
        ),
    ]
