# Generated by Django 3.1.6 on 2021-02-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210221_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Senior'), (3, 'External'), (4, 'Admin')], verbose_name='user type'),
        ),
    ]
