FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y mariadb-server mariadb-client python3-pip libmariadbclient-dev

RUN /etc/init.d/mysql start

WORKDIR /app
COPY server/ /app/server/

RUN pip3 install -r server/requirements.txt
ENV PYTHONPATH="${PYTHONPATH}:/app/server"
