# Generated by Django 3.1.4 on 2021-02-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, default=None, null=True, verbose_name='Url')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('_is_menu', models.BooleanField(verbose_name='Is menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.menuitembase',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.menuitembase',),
        ),
        migrations.AddField(
            model_name='menuitembase',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.menu', verbose_name='Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitembase',
            unique_together={('menu', 'order'), ('menu', 'name')},
        ),
    ]
