# Generated by Django 3.1.4 on 2021-02-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('website', '0002_auto_20210202_0130'), ('website', '0003_auto_20210202_0132'), ('website', '0004_auto_20210202_0234'), ('website', '0005_auto_20210203_0006')]

    dependencies = [
        ('website', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('_url', models.URLField(blank=True, default=None, null=True, verbose_name='Url')),
                ('_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.menuitem')),
            ],
            bases=('website.menuitem',),
        ),
        migrations.CreateModel(
            name='MenuThroughRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(verbose_name='Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_relation', to='website.menuitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_relations', to='website.menu')),
            ],
            options={
                'unique_together': {('order_num', 'menu'), ('item', 'menu')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', through='website.MenuThroughRel', to='website.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuthroughrel',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_relation', to='website.menu'),
        ),
        migrations.RenameModel(
            old_name='MenuThroughRel',
            new_name='MenuRel',
        ),
    ]
