# Generated by Django 3.1.4 on 2021-02-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_backend-menu-model_20210203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, default=None, null=True, verbose_name='Url')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_menu', models.BooleanField(verbose_name='Is menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.AlterUniqueTogether(
            name='menurel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menurel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='menurel',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuRel',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.menuitembase',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.menuitembase',),
        ),
        migrations.AddField(
            model_name='menuitembase',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.menu', verbose_name='Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitembase',
            unique_together={('menu', 'name'), ('menu', 'order')},
        ),
    ]
