# Generated by Django 3.1.4 on 2021-02-02 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210202_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.menuitem')),
            ],
            bases=('website.menuitem',),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Url'),
        ),
        migrations.CreateModel(
            name='MenuThroughRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(verbose_name='Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_relations', to='website.menuitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_relations', to='website.menu')),
            ],
            options={
                'unique_together': {('order_num', 'menu'), ('item', 'menu')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', through='website.MenuThroughRel', to='website.MenuItem'),
        ),
    ]
