# Generated by Django 3.1.4 on 2021-02-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210202_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuthroughrel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_relation', to='website.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuthroughrel',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_relation', to='website.menu'),
        ),
    ]
