# Generated by Django 3.1.6 on 2021-02-14 02:57

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_backend-menu-admin_210211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentObjectBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='component')),
                ('db_type', models.CharField(blank=True, choices=[('text', 'text'), ('image', 'image'), ('menu', 'menu'), ('page', 'page'), ('list', 'list'), ('dict', 'dict')], max_length=5, verbose_name='database type')),
                ('attributes', jsonfield.fields.JSONField(blank=True, default='{}', verbose_name='attributes')),
                ('order', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'base content object',
                'verbose_name_plural': 'base content objects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'image',
            },
        ),
        migrations.CreateModel(
            name='ContentCollection',
            fields=[
                ('contentobjectbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentobjectbase')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='is ordered')),
            ],
            options={
                'verbose_name': 'content collection',
                'verbose_name_plural': 'content collections',
            },
            bases=('website.contentobjectbase',),
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('contentobjectbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentobjectbase')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'text content object',
                'verbose_name_plural': 'text content objects',
            },
            bases=('website.contentobjectbase',),
        ),
        migrations.CreateModel(
            name='ContentCollectionList',
            fields=[
                ('contentcollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentcollection')),
            ],
            options={
                'verbose_name': 'content collection list',
                'verbose_name_plural': 'content collection lists',
            },
            bases=('website.contentcollection',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('contentobjectbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentobjectbase')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_objects', to='website.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'page content object',
                'verbose_name_plural': 'page content objects',
            },
            bases=('website.contentobjectbase',),
        ),
        migrations.AddField(
            model_name='contentobjectbase',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.contentcollection', verbose_name='collection'),
        ),
        migrations.CreateModel(
            name='ContentMenu',
            fields=[
                ('contentobjectbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentobjectbase')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_objects', to='website.menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'menu content object',
                'verbose_name_plural': 'menu content objects',
            },
            bases=('website.contentobjectbase',),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('contentobjectbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.contentobjectbase')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_objects', to='website.image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image content object',
                'verbose_name_plural': 'image content objects',
            },
            bases=('website.contentobjectbase',),
        ),
    ]
