# Generated by Django 3.1.4 on 2021-02-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210202_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuThroughRel',
            new_name='MenuRel',
        ),
    ]
