# Generated by Django 3.1.4 on 2021-02-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210207_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitembase',
            name='is_menu',
        ),
        migrations.AlterField(
            model_name='menuitembase',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.menu', verbose_name='Menu'),
        ),
    ]
