# Generated by Django 3.1.4 on 2021-02-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_backend-content-object-model_210214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.URLField(verbose_name='root URL')),
                ('api_root_url', models.URLField(verbose_name='API root URL')),
                ('banner_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='banner_content', to='website.contentcollection', verbose_name='banner content')),
                ('footer_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='footer_content', to='website.contentcollection', verbose_name='footer content')),
                ('root_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.page', verbose_name='root page')),
            ],
            options={
                'verbose_name': 'site manager',
            },
        ),
    ]
