# Generated by Django 3.1.4 on 2021-02-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210207_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitembase',
            name='_is_menu',
            field=models.BooleanField(default=False, verbose_name='Is menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitembase',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menuitembase',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
