# Generated by Django 3.1.4 on 2021-02-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210203_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='_page',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='_url',
            new_name='url',
        ),
    ]
