# Generated by Django 3.1.6 on 2021-02-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_backend-site-model-singelton-initialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='pagedraft',
            options={'verbose_name': 'page draft', 'verbose_name_plural': 'page drafts'},
        ),
    ]
