# Generated by Django 3.1.6 on 2021-02-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge-backend-page-model-with-main_210215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_draft',
        ),
        migrations.AddField(
            model_name='pagedraft',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_draft', to='website.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
