# Generated by Django 3.1.6 on 2021-02-28 13:39

import django.db.models.deletion
import website.models.redirects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_backend-page-admin_20210221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(max_length=255, unique=True, validators=[website.models.redirects.from_path_validator], verbose_name='from path')),
                ('url', models.URLField(blank=True, default=None, null=True, verbose_name='url')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
            },
        ),
    ]
