# Generated by Django 3.1.7 on 2021-04-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('website', '0010_auto_20210401_2035'), ('website', '0011_auto_20210408_2011'), ('website', '0012_auto_20210408_2051'), ('website', '0013_auto_20210408_2103'), ('website', '0014_auto_20210408_2126')]

    dependencies = [
        ('website', '0009_backend-redirects_20210228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemodel',
            options={'verbose_name': 'site manager', 'verbose_name_plural': 'site manager'},
        ),
        migrations.AddField(
            model_name='page',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish time'),
        ),
        migrations.AddField(
            model_name='page',
            name='unpublish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='unpublish time'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_page_page_en', to='website.contentobjectbase', verbose_name='english content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_sv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_page_page_sv', to='website.contentobjectbase', verbose_name='swedish content'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('name', 'parent'), ('slug', 'parent')},
        ),
        migrations.RemoveField(
            model_name='page',
            name='published_at',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('page_type', models.CharField(max_length=255, verbose_name='page type')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('published', models.BooleanField(default=False, verbose_name='is published')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('unpublish_time', models.DateTimeField(blank=True, null=True, verbose_name='unpublish time')),
                ('last_edited_at', models.DateTimeField(auto_now=True, verbose_name='last edited at')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='created by')),
                ('views', models.IntegerField()),
                ('content_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_news_page_en', to='website.contentobjectbase', verbose_name='english content')),
                ('content_sv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_news_page_sv', to='website.contentobjectbase', verbose_name='swedish content')),
                ('first_published_at', models.DateField(blank=True, null=True, verbose_name='first published at')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=255, verbose_name='page type')),
                ('last_edited_at', models.DateField(auto_now=True, verbose_name='last edited at')),
                ('content_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_draft_en', to='website.contentobjectbase', verbose_name='english content')),
                ('content_sv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_draft_sv', to='website.contentobjectbase', verbose_name='swedish content')),
                ('new', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_draft', to='website.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'news draft',
                'verbose_name_plural': 'news drafts',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='first_published_at',
            field=models.DateField(blank=True, null=True, verbose_name='first published at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_edited_at',
            field=models.DateTimeField(verbose_name='last edited at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
