# Generated by Django 3.1.6 on 2021-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_backend-redirects_20210228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemodel',
            options={'verbose_name': 'site manager', 'verbose_name_plural': 'site manager'},
        ),
    ]
