# Generated by Django 3.1.6 on 2021-04-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210401_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='first_published_at',
            field=models.DateField(blank=True, null=True, verbose_name='publish time'),
        ),
        migrations.AddField(
            model_name='page',
            name='first_published_at',
            field=models.DateField(blank=True, null=True, verbose_name='publish time'),
        ),
        migrations.CreateModel(
            name='NewsDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=255, verbose_name='page type')),
                ('last_edited_at', models.DateField(auto_now=True, verbose_name='last edited at')),
                ('content_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_draft_en', to='website.contentobjectbase', verbose_name='english content')),
                ('content_sv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_draft_sv', to='website.contentobjectbase', verbose_name='swedish content')),
                ('new', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_draft', to='website.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'news draft',
                'verbose_name_plural': 'news drafts',
            },
        ),
    ]
