# Generated by Django 3.1.6 on 2021-03-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_backend-site-admin_20210302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentobjectbase',
            name='parent_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='containing page'),
            preserve_default=False,
        ),
    ]
