# Generated by Django 3.1.6 on 2021-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_backend-content-object-tree-selector_20210411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='text'),
            preserve_default=False,
        ),
    ]
