# Generated by Django 3.1.7 on 2021-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210408_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='first_published_at',
            field=models.DateField(blank=True, null=True, verbose_name='first published at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_edited_at',
            field=models.DateTimeField(verbose_name='last edited at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='first_published_at',
            field=models.DateField(blank=True, null=True, verbose_name='first published at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_edited_at',
            field=models.DateTimeField(verbose_name='last edited at'),
        ),
    ]
