# Generated by Django 3.1.6 on 2021-04-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210418_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentobjectbase',
            name='component',
        ),
    ]
