# Generated by Django 3.1.7 on 2021-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210408_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited at'),
        ),
    ]
