# Generated by Django 3.1.7 on 2021-04-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210408_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('name', 'parent'), ('slug', 'parent')},
        ),
    ]
