# Generated by Django 3.1.7 on 2021-04-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_contentobjectbase_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentobjectbase',
            name='containing_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='containing page'),
        ),
    ]
