name: On pullrequest tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        
      - name: Move to backend
        run: cd server
        
      - name: Django Test CI
        # You may pin to the exact commit or the version.
        # uses: UKnowWhoIm/django-test-action@43d1964e6fbb32ebe3e6f82d63b8291764cad3a7
        uses: django-test-action@v0.6
        with:
          settings-dir-path: project_settings/
          requirements-file: requirements.txt
