name: On pullrequest tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      server-dir: ./server

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: 

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python packages
        run: pip3 install -r requirements.txt
        working-directory: ${{ env.server-dir }}

      - name: Add django root to PYTHONPATH
        run: export PYTHONPATH="${PYTHONPATH}:${{ env.server-dir }}"

      - name: Run Django tests
        run: python3 scripts/manage.py test
        working-directory: ${{ env.server-dir }}
