name: On pullrequest tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    container: ghcr.io/fysiksektionen/hemsidan:server-dev

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Install python packages
        run: pip3 install -r requirements.txt
        working-directory: ./server

      # - uses: samin/mysql-action@v1
      #   with:
      #     mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
      #     mysql root password: '' # Required if "mysql user" is empty, default is empty. The root superuser password
      #     mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Of course you can use secrets, too

      - name: Start MySQL
        run: /etc/init.d/mysql start

      - name: Run Django tests
        run: python3 scripts/manage.py test
        working-directory: ./server
